### ISSUE TITLE
PyOracc could not parse token

### ISSUE THREAD

**Issue by epageperron** [cdli-gh/pyoracc#3]
$ pyoracc -i /data/atf.atf
Atf type: cdli
Info: Failed with message: PyOracc could not parse token ‘LexToken(REFERENCE,u’colophon’,31,558)’. (line 31) in /data/atf.atf
e$

using the last version of the cdli atf dump

**Comment by jayanthkmr** [comment]
This issue is resolved now. There are other Atf issues so we can close this and create new or update this.

**Comment by jayanthkmr** [comment]
Solving one by one:
https://docs.google.com/spreadsheets/d/1Tr98H0cJcFMD6_f6_60aMMt0p93rfnRXUQBDaiwsq_s/edit?usp=sharing

**Comment by epageperron** [comment]
Ok great! It wasn't just a collected error but made the script fail so I will close the issue and create a new one at my next test makes the script exit again.
