### ISSUE TITLE
I think the output is -v by default

### ISSUE THREAD

**Issue by epageperron** [cdli-gh/pyoracc#33]
I think the output is -v by default? Since in the readme we are expected to add the switch to get verbose output, it is possible to check the behavior?

**Comment by jayanthkmr** [comment]
-v "verbose" is disabled by default and if you enable it, you would get the state transitions while parsing as output. Don't use -v as it is for debugging purposes.

https://github.com/cdli-gh/pyoracc/blob/master/pyoracc/wrapper/cli.py#L36

**Comment by epageperron** [comment]
Hm. I didn't use it last time, I just ran the exact same command now and this time the state switching didn't appear. I have no idea why it showed the last time !

**Comment by jayanthkmr** [comment]
Note that using the verbose option will also create a parselog.txt file, containing the log output along with displaying it on command line. The verbose output contains the lexical symbols, the parse grammer table and the LR parsing table states.

Also note that, "first time usage" with any atf format will always display the parse tables irrespective of verbose switch.

I have mentioned this in [Usage](https://github.com/cdli-gh/pyoracc/blob/master/README.md#usage)

**Comment by epageperron** [comment]
Noted ! thanks
